apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controlplanes
  namespace: demos
spec:
  destination:
    namespace: demos
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '**/ControlPlane.yaml'
      jsonnet: {}
      recurse: true
    path: murph-azure-westus/demos
    repoURL: https://github.com/djeremiah/crossplane-by-example
    targetRevision: HEAD
  syncPolicy:
    automated: {}
