apiVersion: spaces.upbound.io/v1beta1
kind: ControlPlane
metadata:
  name: thursday
  namespace: demos
spec:
  crossplane:
    autoUpgrade:
      channel: Rapid
  deletionPolicy: Delete
  managementPolicies:
  - '*'
  writeConnectionSecretToRef:
    name: thursday-kubeconfig
